services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: appdb

  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db:5432/appdb -user=app -password=app migrate
    volumes:
      - ./db/migrations:/flyway/sql
